# Generated by Django 3.2.4 on 2021-07-08 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MemberGroup', '0003_alter_skill_valueskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksample',
            name='DateCreate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
