# Generated by Django 3.2.4 on 2021-07-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberGroup', '0006_likeworksample_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergroup',
            name='AboutMe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
