# Generated by Django 3.2.4 on 2021-07-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('MemberGroup', '0007_membergroup_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberGroup.membergroup')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
