# Generated by Django 3.2.4 on 2022-03-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemberGroup', '0011_auto_20220328_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membergroup',
            old_name='Is_Checked',
            new_name='Is_Active',
        ),
    ]
