# Generated by Django 3.2.4 on 2021-08-02 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_datetimejoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=65)),
                ('Technologies', models.CharField(max_length=100)),
                ('DeadLineByUser', models.IntegerField()),
                ('DeadLineFinally', models.IntegerField(blank=True, null=True)),
                ('BudgetByUser', models.IntegerField()),
                ('BudgetFinally', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
