# Generated by Django 3.2.4 on 2021-08-02 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='DateSubmit',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='StateProject',
            field=models.CharField(choices=[('Checking', 'Checking'), ('WorkingOn', 'WorkingOn'), ('Ended', 'Ended')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
