# Generated by Django 3.2.4 on 2021-08-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_project_descriptionadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='DescriptionAdmin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='StateProject',
            field=models.CharField(choices=[('Cancel', 'لغو'), ('Checking', 'در حال بررسی'), ('WorkingOn', 'در دست ساخت'), ('Ended', 'تمام شده')], max_length=10),
        ),
    ]
