# Generated by Django 3.2.4 on 2021-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210802_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
