# Generated by Django 3.2.4 on 2021-08-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='StateProject',
            field=models.CharField(choices=[('Cancel', 'لغو'), ('Checking', 'در حال بررسی'), ('WaitPay', 'در انتظار پرداخت'), ('WorkingOn', 'در دست ساخت'), ('Ended', 'تمام شده')], max_length=10),
        ),
    ]
