# Generated by Django 3.2.4 on 2021-08-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_project_stateproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='BudgetByUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='BudgetFinally',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='DeadLineByUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='DeadLineFinally',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
